<?php
  echo "Numero control:".$_POST['numeroControl']."<br>".
        "Nombre:".$_POST['nombre']."<br>".
        "apPaterno:".$_POST['apPaterno']."<br>".
        "apMaterno:".$_POST['apMaterno']."<br>".
        "apPaterno:".$_POST['apPaterno']."<br>".
        "fechaNacimiento:".$_POST['fechaNacimiento']."<br>".
        "curp:".$_POST['curp']."<br>".
        "rdSexo:".$_POST['rdSexo']."<br>".
        "rdEstadoCivil:".$_POST['rdEstadoCivil']."<br>".
        "calle:".$_POST['calle']."<br>".
        "numeroCasa:".$_POST['numeroCasa']."<br>".
        "colonia:".$_POST['colonia']."<br>".
        "CP:".$_POST['CP']."<br>".
        "ciudad:".$_POST['ciudad']."<br>".
        "municipio:".$_POST['municipio']."<br>".
        "estado:".$_POST['estado']."<br>".
        "celular:".$_POST['celular']."<br>".
        "correo:".$_POST['correo']."<br>".
        "telCasa:".$_POST['telCasa']."<br>".
        "slCarreraEgreso:".$_POST['slCarreraEgreso']."<br>".
        "fechaEgreso:".$_POST['fechaEgreso']."<br>".
        "rdTitulado:".$_POST['rdTitulado']."<br>".
        "ingles:".$_POST['ingles']."<br>".
        "slOtroIdioma:".$_POST['slOtroIdioma']."<br>".
        "otroIdiomaPorcen:".$_POST['otroIdiomaPorcen']."<br>".
        "paquetesComp:".$_POST['paquetesComp']."<br>".
        "rdCalidadDocente:".$_POST['rdCalidadDocente']."<br>".
        "rdPlanEstudio:".$_POST['rdPlanEstudio']."<br>".
        "rdProyectoInvestigacion:".$_POST['rdProyectoInvestigacion']."<br>".
        "rdEnfasisInvestigacion:".$_POST['rdEnfasisInvestigacion']."<br>".
        "rdSatisfacionCondiciones:".$_POST['rdSatisfacionCondiciones']."<br>".
        "rdExperienciaObtenida:".$_POST['rdExperienciaObtenida']."<br>".
        "rdActividad:".$_POST['rdActividad']."<br>".
        "rdQueEstudia:".$_POST['rdQueEstudia']."<br>".
        "rdTiempoTranscurrido:".$_POST['rdTiempoTranscurrido']."<br>".
        "rdMedioObtenerEmpleo:".$_POST['rdMedioObtenerEmpleo']."<br>".
        "rdRequisitosContratacion:".$_POST['rdRequisitosContratacion']."<br>".
        "slOtroIdioma:".$_POST['slOtroIdioma']."<br>".
        "idiomaHabla:".$_POST['idiomaHabla']."<br>".
        "idiomaEscribe:".$_POST['idiomaEscribe']."<br>".
        "idiomaLee:".$_POST['idiomaLee']."<br>".
        "idiomaEscucha:".$_POST['idiomaEscucha']."<br>".
        "rdAntiguedadEmpleo:".$_POST['rdAntiguedadEmpleo']."<br>".
        "anioIngreso:".$_POST['anioIngreso']."<br>".
        "rdSalarioMinimo:".$_POST['rdSalarioMinimo']."<br>".
        "anioIngreso:".$_POST['anioIngreso']."<br>".
        "rdJerarquiaTrabajo:".$_POST['rdJerarquiaTrabajo']."<br>".
        "rdCondicionTrabajo:".$_POST['rdCondicionTrabajo']."<br>".
        "rdRelacionAreaFormacion:".$_POST['rdRelacionAreaFormacion']."<br>".
        "rdOrganismo:".$_POST['rdOrganismo']."<br>".
        "txaGiroPrinEmpresa:".$_POST['txaGiroPrinEmpresa']."<br>".
        "txRazonSocial:".$_POST['txRazonSocial']."<br>".
        "calleEmpresa:".$_POST['calleEmpresa']."<br>".
        "numeroEmpresa:".$_POST['numeroEmpresa']."<br>".
        "coloniaEmpresa:".$_POST['coloniaEmpresa']."<br>".
        "cpEmpresa:".$_POST['cpEmpresa']."<br>".
        "ciudadEmpresa:".$_POST['ciudadEmpresa']."<br>".
        "municipioEmpresa:".$_POST['municipioEmpresa']."<br>".
        "estadoEmpresa:".$_POST['estadoEmpresa']."<br>".
        "telefonoEmpresa:".$_POST['telefonoEmpresa']."<br>".
        "telExt:".$_POST['telExt']."<br>".
        "fax:".$_POST['fax']."<br>".
        "emailEmpresa:".$_POST['emailEmpresa']."<br>".
        "paginaWebEmpresa:".$_POST['paginaWebEmpresa']."<br>".
        "rdSectorPrimario:".$_POST['rdSectorPrimario']."<br>".
        "rdSectorSecundario:".$_POST['rdSectorSecundario']."<br>".
        "rdSectorTerciario:".$_POST['rdSectorTerciario']."<br>".
        "rdTamanioEmpresa:".$_POST['rdTamanioEmpresa']."<br>".
        "rdEficienciaLaboral:".$_POST['rdEficienciaLaboral']."<br>".
        "rdFormacionAcademica:".$_POST['rdFormacionAcademica']."<br>".
        "rdPracticasProfesionales:".$_POST['rdPracticasProfesionales']."<br>".
        "rdValoraCampoEstudio:".$_POST['rdValoraCampoEstudio']."<br>".
        "rdTitulacion:".$_POST['rdTitulacion']."<br>".
        "rdExperienciaLaboral:".$_POST['rdExperienciaLaboral']."<br>".
        "rdHabilidadProblemas:".$_POST['rdHabilidadProblemas']."<br>".
        "rdPosicionInstituto:".$_POST['rdPosicionInstituto']."<br>".
        "rdReferencias:".$_POST['rdReferencias']."<br>".
        "rdPersonalidadActitud:".$_POST['rdPersonalidadActitud']."<br>".
        "rdCapacidadLiderazgo:".$_POST['rdCapacidadLiderazgo']."<br>".
        "rdOtrosAspectosValoraEmpresa:".$_POST['rdOtrosAspectosValoraEmpresa']."<br>".
        "rdTomariaCursos:".$_POST['rdTomariaCursos']."<br>".
        "rdTomariaPostgrado:".$_POST['rdTomariaPostgrado']."<br>".
        "rdOrganizacionSocial:".$_POST['rdOrganizacionSocial']."<br>".
        "rdOrganismoProfesionistas:".$_POST['rdOrganismoProfesionistas']."<br>".
        "rdAsociacionEgresados:".$_POST['rdAsociacionEgresados']."<br>".
        "comentariosSugerencias:".$_POST['comentariosSugerencias']
  ;
 ?>
